### ISSUE TITLE
AJAX authorization

### ISSUE THREAD

**Issue by jamesgol** [afragen/wp-dependency-installer#10]
It looks like ajax_router should be doing a check on current_user_can( 'update_plugins' ).  I see install() has a check but I suspect the logic is wrong.

```
            if ( $this->is_installed( $slug ) && ! current_user_can( 'update_plugins' ) ) {
                return false;
            }
```

I'm guessing this should be || instead of &&

**Comment by afragen** [comment]
Thanks. I think you're correct.
