### ISSUE TITLE
Better format for autoloaders

### ISSUE THREAD

**Issue by afragen** [afragen/wp-dependency-installer#11]
@mgibbs189 take a look at the develop branch. 

I've refactored the whole repo to better align as a framework.
1. Moved plugin to `example` directory
2. Removed the `wp-dependencies.json` file
3. Added `WP Rest API` as a plugin optional install example to `wp-dependencies-example.php`
4. Refactored to better accommodate an autoloader. This means that loading the class no longer initiates the process but I included a `run()` command to do this.

``` php
include_once( __DIR__ . '/vendor/wp-install-dependencies/wp-dependency-installer.php' );
WP_Dependency_Installer::instance()->run();
```

after loading the class.

Thoughts?

**Comment by mgibbs189** [comment]
@afragen haven't tested it yet, but the code looks good. Could you tell me more about this line?:

``` php
WP_Dependency_Installer::instance()->run();
```

E.g. why that's not appended to the end of `wp-dependency-installer.php`? You mentioned it's to support an autoloader. Could you tell me more about that?

**Comment by afragen** [comment]
If you load the class file via an autoloader it won't load the file until you issue a command. I needed a command to actually run the config stuff if an autoloader is used.

It means that when not using an autoloader, including the file won't run anything. If we went back to running the command on include it might enter an infinite loop. Didn't test that part but I can. I'll see what happens if I add back ability to run on include.

Not sure if it makes more sense to be consistent in how to run the framework regardless of how the class is loaded.

**Comment by afragen** [comment]
I tested and it doesn't seem to matter if is loaded in both ways, so I added the run on load back in.

I updated README, can you make sure it makes sense re: including and autoloaders?

**Comment by afragen** [comment]
Created a composer package. Now definitely use composer autoload.php
`composer require afragen/wp-dependency-installer`
