### ISSUE TITLE
after 1.3 update nothing seems to be installing anymore

### ISSUE THREAD

**Issue by senlin** [afragen/wp-dependency-installer#15]
As per title, I cannot get it to do anything anymore. Was working before on 1.1, but I have to admit that I'm pretty new to this class and the last time I had it working was a month ago.
Can anyone get it to work on a vanilla install?

**Comment by afragen** [comment]
Can you point to the plugin/theme that you're using it on?

**Comment by afragen** [comment]
I believe this line https://github.com/senlin/lean-wp/blob/develop/lean-wp.php#L25 should be like https://github.com/senlin/lean-wp/blob/develop/vendor/afragen/wp-dependency-installer/example-plugin/test-dependency-installer.php#L14

There might be some difference.

**Comment by senlin** [comment]
wow, now I feel really stupid (and embarrassed)...

Nevertheless, thanks Andy!

**Comment by afragen** [comment]
Does that mean that it now works?

**Comment by senlin** [comment]
:) yup it does indeed mean that 👍
