### ISSUE TITLE
Undefined index: source when activating

### ISSUE THREAD

**Issue by JiveDig** [afragen/wp-dependency-installer#21]
This came up in a theme I run the dependency installer with. It's a new one to me.

```
[10-Oct-2018 14:33:47 UTC] PHP Notice:  Undefined index: source in 
/Users/nick/Documents/sites/mailaw/wp-content/themes/mai-law-pro-
master/includes/dependencies/wp-dependency-installer.php on line 427
```
https://github.com/maithemewp/mai-law-pro/issues/1

**Comment by JiveDig** [comment]
The theme is using v1.4.3

**Comment by JiveDig** [comment]
And my JSON config is:
```
[
	{
		"name": "Mai Theme Engine",
		"host": "github",
		"slug": "mai-theme-engine/mai-theme-engine.php",
		"uri": "maithemewp/mai-theme-engine",
		"branch": "master",
		"optional": false,
		"token": null
	}
]
```

**Comment by afragen** [comment]
I’ve seen this, but only the first time the framework runs and then it disappeared. 

I have really had the energy to track it down - yet. 😉

**Comment by afragen** [comment]
I think it happens because I’ve added the ability to set the timeout from a filter to override the default. 

Seems like I just need to set the variable to the default if it doesn’t exist.

**Comment by JiveDig** [comment]
Just submitted PR. Hopefully it helps. Feel free to tweak/change.  We're releasing our next theme on StudioPress in less than a week and would love to get this fix in there.

**Comment by afragen** [comment]
@JiveDig I believe the error was triggered when a _required_ plugin was installed/activated.

**Comment by JiveDig** [comment]
Wow great! Yes I only use it for a required plugin. Good find, thanks!!!!
