### ISSUE TITLE
Auto refresh plugins page after installation/activation of plugin

### ISSUE THREAD

**Issue by senlin** [afragen/wp-dependency-installer#25]
Hi @afragen - how are you?

We're using the Dependency Installer for our [Classic Editor Addon plugin](https://github.com/senlin/classic-editor-addon) (to install the Classic Editor plugin).

From one of our users we received this "[report](https://github.com/senlin/classic-editor-addon/issues/4)":

> If you add/install/activate your plugin without first installing the “Classic Editor” plugin, your plugin provides the “Install Now” link – which is excellent. However, once it has installed/activated “Classic Editor” via this link, it does not refresh the list of plugins – hence it does not look as though “Classic Editor” has been installed & activated. You have to then refresh the plugins page to show it in the list.

So the question is whether there is a way to auto-refresh the plugins page after installation/activation of the depending plugin?

Looking forward to hearing from you.

Cheers,
Pieter

**Comment by afragen** [comment]
The install/activate occurs via an admin-ajax.php call. This means that the page doesn’t refresh. You are missing a parameter in your `wp-dependencies.json` on whether the install is optional or not. Leaving it off makes this optional. If you look at the example you can see that setting `"optional":"false"` will automatically install and activate the plugin.

Regardless you will need to refresh the plugin page to see the results.

You should also do a make sure you’re using the latest version of the `wp-dependency-Installer`, it’s at version 1.4.6. Update your composer.json to use `^1.4`

**Comment by senlin** [comment]
Hi Andy, Thanks for your swift reply. I have tested setting the `"optional"`-parameter to `false` and that indeed works much better and in this case also makes much more sense as one doesn't go without the other.

Also thanks for the tip on updating the version, I have now also subscribed to version updates :)

Wish you a great weekend!
