### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by JiveDig** [afragen/wp-dependency-installer#26]
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'PAnD' not found in /Users/JiveDig/ValetSites/merlin/wp-includes/class-wp-hook.php on line 286`

When I remove dependency installer I don't see this. Using the latest from https://raw.githubusercontent.com/afragen/wp-dependency-installer/master/wp-dependency-installer.php, which accordingly to the Releases is `1.4.10`

Similar: https://github.com/afragen/github-updater/issues/453

**Comment by JiveDig** [comment]
FWIW, I'm doing this via my theme's functions.php file:
```
require_once 'includes/dependencies/wp-dependency-installer.php';
WP_Dependency_Installer::instance()->run( dirname( __FILE__ ) . '/includes/dependencies' );
```
And if I run it later it goes away, but not sure of the consequences:
```
require_once 'includes/dependencies/wp-dependency-installer.php';
add_action( 'admin_init', function() {
	WP_Dependency_Installer::instance()->run( dirname( __FILE__ ) . '/includes/dependencies' );
});
```

**Comment by JiveDig** [comment]
Update: Using via Composer does work. Probably better if I do it that way anyway.
```include_once( __DIR__ . '/vendor/autoload.php' );
WP_Dependency_Installer::instance()->run( __DIR__ );```

**Comment by afragen** [comment]
Designed to run through composer.

**Comment by JiveDig** [comment]
K, if it's not meant to work any other way than with composer (my current themes are not using composer) then I'll close. Updating all my themes now with this.

**Comment by afragen** [comment]
It should run with composer. I don’t think the above code you supplied is correct.

```php
require_once 'includes/dependencies/wp-dependency-installer.php';
add_action( 'admin_init', function() {
	WP_Dependency_Installer::instance()->run( __DIR__  );
});
```
Need to make sure `wp-dependencies.json` is at plugin/theme root.

**Comment by afragen** [comment]
It really does need composer as the dependencies might also require composer’s autoloader.

**Comment by afragen** [comment]
There’s probably a way to make it work without composer but if there are issues it will be difficult to trace.

**Comment by JiveDig** [comment]
All good. My old themes (currently live on quite a few sites) have the older non-composer setup and it has worked well. Only issue would be if they use another plugin that uses the newer version and possibly hit a conflict. Unlikely though.
