### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by mgibbs189** [afragen/wp-dependency-installer#3]
I'll update this comment with feedback from subsequent comments.

**Goals**
This is a drop-in library, allowing plugins to register both **required** and **optional** dependencies.

**Registering Dependencies**
- [x] A plugin can register dependencies via a `wp-dependencies.json` file in the same directory
- [ ] A plugin can register dependencies programmatically (TBA)

**Dependency Config**
- slug (required, e.g. "github-updater")
- label (required, e.g. "GitHub Updater")
- path (required, e.g. "github-updater/github-updater.php")
- uri (required, e.g. "https://github.com/afragen/github-updater")
- optional (optional, default = true)
- branch (optional, default = "master")
- token (optional, default = null) 

~~**Required Dependencies**~~

> Let core handle permissions.
-  ~~Check file permissions~~
-  ~~If writable, each dependency will be automatically installed and activated~~
-  ~~If not writable, treat each dependency as an Optional dependency (e.g. display dependencies on the Plugins page, show a "Download ZIP" link beside each plugin)~~

**Optional Dependencies**
-  ~~Check file permissions~~
- Display each dependency below a plugin's listing on the Plugins page.
  - Won't work for themes adding plugin dependencies
- [ ] If writable, the "Install Now" link should automatically install the plugin and return the user to the Plugins page.
- [ ] If not writable, show a "Download ZIP" link, so user can install manually

**Nag Screen**
- [x] The Plugins page itself serves as the nag screen. If a dependency needs to be installed, the parent plugin will appear with a red background, exactly like other "Updates Available" plugins.

<img src="http://i.imgur.com/IgU7cmP.png" width="620" height="152" />

**Miscellaneous**
- [x] Prevent display of plugin install feedback from automatically installed plugins, cosmetic.

**Comment by afragen** [comment]
Need to update for new json format, with first line as dependent plugin's slug.

Matt, this is pretty extensive.

Nag screen - check https://github.com/afragen/wp-install-dependencies/commit/28d62d70597b3ad724a0b348e00956892cd3a39d

Comment out https://github.com/afragen/wp-install-dependencies/blob/master/install-dependencies/wp-install-dependencies.php#L169 to see nag screen.

**Comment by mgibbs189** [comment]
FYI - I've written a temporary drop-in **specifically** for GitHub Updater: https://github.com/mgibbs189/install-github-updater

As WP Install Dependencies gets further along, it'll make my code unnecessary :wink:

**Comment by afragen** [comment]
Matt,

That looks great! I'd really appreciate a PR or when I have time I'll try to incorporate your methods.

Andy

**Comment by afragen** [comment]
List cleaned up as we should let core handle file permissions.
