### ISSUE TITLE
Local plugin dependency

### ISSUE THREAD

**Issue by nunof07** [afragen/wp-dependency-installer#31]
Feature request: would be nice to have a way to specify local zip files. Currently, the "direct" option only works with URIs.

Thanks for the great work!

**Comment by afragen** [comment]
Have you tried making the Direct URI `file://`?

**Comment by nunof07** [comment]
It does work with `file://` when using full paths, but I couldn't get it to work with a relative path, so it makes it hard to use this in different machines.

**Comment by afragen** [comment]
Sorry, that’s the best idea I have. The framework is about remote installation of dependent plugins not local installation.
