### ISSUE TITLE
GitLab Deploy Tokens

### ISSUE THREAD

**Issue by nunof07** [afragen/wp-dependency-installer#32]
This package supports GitLab Personal Access Tokens. However, these are private tokens for a user.

GitLab also has [Deploy Tokens](https://docs.gitlab.com/ee/user/project/deploy_tokens/), which are configured at the repository level (Settings > Repository > Deploy Tokens), but these don't work with the `private_token` query arg which this package is using.

Not sure how substantial of a change it would be, but it would be a nice addition.

Thanks!

**Comment by afragen** [comment]
Thanks. I’ll take a look at this.

**Comment by afragen** [comment]
It appears _Deploy Tokens_ are using from the command line as in using `git clone`. In order to use such a process I would need to use it via an HTTP GET request.
