### ISSUE TITLE
GitLab option not working

### ISSUE THREAD

**Issue by nunof07** [afragen/wp-dependency-installer#33]
The GitLab option is not working. New URI is needed.

I believe GitLab removed the GET access to the repository archive for security reasons (https://about.gitlab.com/2018/11/28/security-release-gitlab-11-dot-5-dot-1-released/) and now requires access using the API (which is available through GET as well).

New URI:

```
https://gitlab.com/api/v4/projects/{project_id}/repository/archive.zip?private_token={personal_access_token}
```

More info here: https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

The token needs "api" scope for this to work.

The workaround is to use the "direct" option instead of GitLab and use the above URI. You now use the project ID instead of the name/project.

**Comment by nunof07** [comment]
However, "api" scope also includes write permissions, so use with caution.

**Comment by nunof07** [comment]
Also: "This endpoint can be accessed without authentication if the repository is publicly accessible.", so no token needed in those cases, I guess.

**Comment by afragen** [comment]
Thanks for the report I’ll take a look.

**Comment by afragen** [comment]
@nunof07 can you manually switch out the `wp-dependency-installer.php` for the latest change in `develop` and let me know if it's fixed?

https://github.com/afragen/wp-dependency-installer/blob/develop/wp-dependency-installer.php

If it's fixed I'll merge and then a `composer update` will fix everything.

**Comment by nunof07** [comment]
@afragen it does work. Thank You!

I'm using this syntax:

```json
[
  {
    "name": "Plugin Name",
    "host": "gitlab",
    "slug": "slug/slug.php",
    "uri": "gitlab-project-id-here",
    "branch": "master",
    "optional": true,
    "token": "personal-access-token-here"
  }
]
```

**Comment by afragen** [comment]
GitLab should use the `user/repo`. If it doesn’t I’ll need to `urlencode` that part. 

Can you try using the regular URI?

**Comment by nunof07** [comment]
I tried using regular URI and also just `user/repo` but it doesn't work. I then tried manually encoding `user/repo` and it worked.

**Comment by afragen** [comment]
Sorry I was half asleep. Are you reporting that `urlencode( user/repo )` works?

**Comment by nunof07** [comment]
Yes, it should work. I didn't change the code to test, but I manually wrote the encoded string into the config, so it should have the same effect.

**Comment by afragen** [comment]
Great, I think I know what to do to fix this. I’ll get something pushed to `develop` and ping when it’s done for testing. Thanks.

**Comment by afragen** [comment]
Fix pushed. Please let me know if it works on your end.

**Comment by nunof07** [comment]
It is working. Thanks! 🎉

**Comment by afragen** [comment]
`composer update` please,  🚀

**Comment by afragen** [comment]
@nunof07 I made a small update from `urlencode()` to `rawurlencode()` for WPCS. Still in same version number.

**Comment by nunof07** [comment]
@afragen thanks. I tried again after updating and it's still working.
