### ISSUE TITLE
How to contribute to develop?

### ISSUE THREAD

**Issue by Raruto** [afragen/wp-dependency-installer#34]
Could you kindly explain better how to test code changes on a wp site?

Here's what I tried:
- when I try to install it locally as a `git folder`, it is not recognized
- passing through wordpress, the system reports that `No valid plugins were found`

**Comment by afragen** [comment]
This is not a plugin. It’s a framework for installing plugins. 

See https://github.com/afragen/github-updater-support or https://github.com/afragen/group-plugin-installer as examples of how to use it.

**Comment by Raruto** [comment]
Yes I know, but there are some things I would like to try to edit here anyway...

_How do you usually do?_

**Comment by afragen** [comment]
Make an issue and we can discuss.

**Comment by Raruto** [comment]
Ok, for testing, I have downloaded the **group installer plugin** and cloned the `git branch` within the [vendor](https://github.com/afragen/group-plugin-installer/tree/master/vendor) folder. Is this a right way?

**Comment by afragen** [comment]
That's as good as any way. I do something similar.

After you make changes to the wp-dependency-installer framework and test them, you would make an issue/PR against a clone of wp-dependency-installer to the `develop` branch.

**Comment by Raruto** [comment]
👌
