### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by afragen** [afragen/wp-dependency-installer#4]
So I thought that `WP Dependency Installer` sounded better that `WP Install Dependencies`.

Two main reasons.
1. More active tense to name.
2. Slightly easier to spell :facepunch: 

Sorry @mgibbs189 you will likely have to fork again.

**Comment by mgibbs189** [comment]
@afragen Got it, thanks for the heads up

**Comment by afragen** [comment]
I also got back to using all the hooks you had, so it should look much more familar. I also added support for adding plugins from w.org, because it seems silly not to.

**Comment by mgibbs189** [comment]
:+1: I like the change too. Feel free to close this issue.
