### ISSUE TITLE
Basic Authentication headers?

### ISSUE THREAD

**Issue by Raruto** [afragen/wp-dependency-installer#41]
I also open [this](https://github.com/afragen/github-updater/issues/848) issue here as a reminder on deciding what to do

- 2019-11-05: [Deprecated passwords and authorizations API](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters)
- REST API v3: [Authentication Methods](https://developer.github.com/v3/auth/)

Related:

- https://github.com/afragen/wp-dependency-installer/issues/30

**Comment by afragen** [comment]
I'll have to take a close look at this.
