### ISSUE TITLE
Dedicated repo for Example plugin / theme

### ISSUE THREAD

**Issue by Raruto** [afragen/wp-dependency-installer#42]
Also in order to avoid importing the following files within other depending plugins / themes:

- [/example-plugin](https://github.com/afragen/wp-dependency-installer/tree/develop/example-plugin)
- [/example-plugin/test-dependency-installer.php](https://github.com/afragen/wp-dependency-installer/blob/develop/example-plugin/test-dependency-installer.php)
- [wp-dependencies-example.json](https://github.com/afragen/wp-dependency-installer/blob/develop/wp-dependencies-example.json)

I think it would be much clearer to insert a link, within the readme file, to a sample repo ( plugin or theme ) to easily allow anyone to start playing with this library.

eg. https://github.com/afragen/group-plugin-installer

**Comment by afragen** [comment]
Good idea. I'll create the repo and update the README.

**Comment by Raruto** [comment]
Nice job, maybe I would leave out the command line part to make that folder more easily forkable, installable and testable...

Something like [that](https://github.com/afragen/group-plugin-installer) is much easier / faster to use as starting point for new projects. So you would only use the following command in the readme file: run `composer update` to...
