### ISSUE TITLE
Private Token in JSON file

### ISSUE THREAD

**Issue by Raruto** [afragen/wp-dependency-installer#43]
Currently all private tokens are saved within the `wp-dependencies.json` file.

```
  {
    "name": "GitHub Updater",
    "host": "github",
    "slug": "github-updater/github-updater.php",
    "uri": "afragen/github-updater",
    "branch": "master",
    "optional": false,
    "token": null <-- github private token
  },
```

Although this is a fast solution, it can potentially expose sensitive information on the web ( potentially anyone on the web could access the following file `wp-dependencies.json` )

_It might also make sense to add a `.htaccess` file?_

**_Do you have any other good ideas about it?_**

**Comment by afragen** [comment]
We could just remove the token option but then no private repos?

Using `.htaccess` doesn't help if user is on nginx.

**Comment by Raruto** [comment]
I like the current solution (clear and concise), I think we just have to try to find / document one or more alternative solutions in case of using private keys (for that I was also thinking of an example `.htaccess` file <-- for example within the wiki documents).

_What do you think of something like the following?_

```php
/**
 * Group Plugin Installer
 *
 * @author  Andy Fragen
 * @license MIT
 * @link    https://github.com/afragen/group-plugin-installer
 * @package group-plugin-installer
 */

$config = json_decode(<<<JSON
[
  {
    "name": "GitHub Updater",
    "host": "github",
    "slug": "github-updater/github-updater.php",
    "uri": "afragen/github-updater",
    "branch": "master",
    "optional": false,
    "token": null
  }
]
JSON
, true );

include_once( __DIR__ . '/vendor/autoload.php' );

// TODO: Code refactoring?
// WP_Dependency_Installer::instance()->source = basename( __DIR__ );

// Install and active dependencies.
WP_Dependency_Installer::instance()->load_hooks();
WP_Dependency_Installer::instance()->register( $config );
```

**Comment by afragen** [comment]
I sorta already documented passing an associative array to `register()` in the README instead of using a JSON file.

I don't think I'm understanding this correctly.

**Comment by Raruto** [comment]
> I don't think I'm understanding this correctly.

What i mean is that maybe a wiki should be created with some more detailed information ( otherwise the readme could easily become very large ).

In particular (I think), at least one valid solution must be reported for "securing" your dependencies file.

> I sorta already documented passing an associative array to register() in the README instead of using a JSON file.

However there is no actually examples of usage, and moreover, it forces you to manually convert your JSON file into an associative array (my example was only to try to have a "unique" simple workflow, i.e. copy-pasta-here your current JSON file)

**Comment by afragen** [comment]
I just set it so anyone can edit the wiki here. Have at it. 😉

**Comment by Raruto** [comment]
> I just set it so anyone can edit the wiki here. Have at it. 😉

I immediately do some tests 🤔

**Comment by Raruto** [comment]
It will not be exhaustive but at least it could be a good start: [wp-dependency-installer/wiki](https://github.com/afragen/wp-dependency-installer/wiki)

**Comment by afragen** [comment]
Seems we can close this issue.
