### ISSUE TITLE
Clear admin dismissable notices cache on plugin deactivation

### ISSUE THREAD

**Issue by Raruto** [afragen/wp-dependency-installer#53]
Related to: https://github.com/afragen/wp-dependency-installer/pull/47#issuecomment-586645733

```php
if ( class_exists( '\PAnd' ) && ! \PAnD::is_admin_notice_active( $dismissible ) ) {
  continue;
}
```

Find a way to display dismissed nag notifications again when the plugin is reactivated in a short time ( or define some sort of debug / development mode )

**Comment by afragen** [comment]
The developer may use a filter to set the amount of time this notice is dismissable. To force a reset , the data is stored in the options table with an option name beginning with `pand`.

For development, simply use the filter to set a very short dismissal time. I believe values between 0 and 1 may be used, but I don't completely remember.

https://github.com/afragen/wp-dependency-installer/wiki/Actions-and-Hooks 😉

**Comment by Raruto** [comment]
So any value between 0 and 0.5 will be fine?

```php
add_filter(
  'wp_dependency_timeout',
  function( $timeout, $source ) {
    return 0.1;
  },
  15,
  2
);
```

[persist-admin-notices-dismissal.php#L116](https://github.com/collizo4sky/persist-admin-notices-dismissal/blob/2d7d8bb3cba631ad227c92296a4b675d7cbc71d7/persist-admin-notices-dismissal.php#L116)

**Comment by afragen** [comment]
Only one way to find out.

**Comment by Raruto** [comment]
Nope, I don't think it's actually possible, any value between 0 and 1 is automatically converted to "1 day".

Anyway don't worry, I'll take a better look.
