### ISSUE TITLE
Remove json "host" arg

### ISSUE THREAD

**Issue by mgibbs189** [afragen/wp-dependency-installer#6]
I think we should auto-detect the `host` from the `uri` arg. @afragen what do you think?

``` json
{
    "name": "GitHub Updater",
    "slug": "github-updater/github-updater.php",
    "uri": "https://github.com/afragen/github-updater",
    "branch": "master",
    "optional": false,
    "token": null
},
```

**Comment by afragen** [comment]
We can autodetect but, my logic for not was, why go through an extra function or two to figure it out when we can have the developer just declare it. The dev is already entering the other data in the JSON.

**Comment by mgibbs189** [comment]
IMO it's just a matter of convenience. Seems counter-productive to require the `host`, when we can easily grab it from the `uri` with minimal extra logic.

E.g. https://github.com/afragen/wp-dependency-installer/pull/5/files#diff-752528f8a0e18edf2b3f3f997c8ecaaaR117

**Comment by afragen** [comment]
The benefit is that you would then allow for a shortened input of just owner/repo for the URI. This shortened input is used for GHU and WP Pusher. I'm not sure if there are other similar products but since those 2 allow it devs might be used to a similar input. 

There's no real downside, it's just part of the json spec. Maybe?

**Comment by mgibbs189** [comment]
@afragen Let's support both then :wink: 

`uri` could be either either a full URL or partial. If the user doesn't specify a `host`, we'll auto-detect.

**Comment by afragen** [comment]
Sounds like a plan.

**Comment by afragen** [comment]
https://github.com/afragen/wp-dependency-installer/commit/854b7b23e2ecb8710c3117271986dd41946fb365

This should account for using `host` or not and shorthand `<owner>/<repo>` as `uri`
