### ISSUE TITLE
Feature: allow requiring a version number range

### ISSUE THREAD

**Issue by cliffordp** [afragen/wp-dependency-installer#64]
Maybe my plugin requires `gravityforms/gravityforms.php` but it should require Gravity Forms v2.0+ or say version 3 is coming out soon and I know I didn't update my code for it yet so I need to require at least v2.0 up to anything less than v3.0 -- basically the equivalent of `~2.0` from https://getcomposer.org/doc/articles/versions.md#writing-version-constraints

This would also be helpful for preventing accidentally clicking "Update" like we all do blindly sometimes when GF v3.0 comes out and shows up in the wp-admin dashboard.

**Comment by afragen** [comment]
This is very out of scope for this framework. I would suggest using composer for this feature.
