### ISSUE TITLE
Configuration option to require commercial plugins without direct download URI 

### ISSUE THREAD

**Issue by herrschuessler** [afragen/wp-dependency-installer#66]
Hi @afragen,

is there an option to require plugins to be installed without a download URI? This would allow me to require the installation of commercial plugins like ACF Pro or WPML by direct upload of the plugin zip.

**Comment by afragen** [comment]
The library is designed to install a dependency for elsewhere. 

I'm not certain I understand your use case. Do you want a notification that a dependency needs to be installed and to go away once it is installed?

You might be able to include the zip in your project and use the direct link method to point to the local zip.

**Comment by herrschuessler** [comment]
> Do you want a notification that a dependency needs to be installed and to go away once it is installed?

Yes, that's exactly what I was looking for, sorry if I didn't make that clear. I was just wondering if there's an "official" way to do that, but it looks like that this isn't really the scope of this package. Thanks for making that clear.
