### ISSUE TITLE
Network Activate or not

### ISSUE THREAD

**Issue by afragen** [afragen/wp-dependency-installer#7]
@mgibbs189 I think the use case is as follows.

A network activated plugin with dependencies needs to have those dependencies network activated. If the activation is on a subsite or a single install then it should not be network activated.

Theme dependencies should never be network activated.

**Comment by mgibbs189** [comment]
@afragen sounds right

**Comment by afragen** [comment]
If we set the default to network activate it won't affect a single site install and since on a multisite install only the superadmin can install plugins it would activate network wide.

The only catch here is that themes with dependencies would have network activated plugins when a theme is only really active on a subsite.

Solving this may mean adding something to the JSON. Do we want to do this?

**Comment by afragen** [comment]
Starting to get overly complex. Simpler just to network activate in all instances. This will clearly mean any theme dependencies don't fatal if theme not active.

Seems like that's more of an issue for the theme/plugin dev?

**Comment by afragen** [comment]
https://github.com/afragen/wp-dependency-installer/commit/12df7b22763bca83fe38919ac2d09ffea7e2a01f

I guess we can come back to this.

**Comment by afragen** [comment]
Network activate if on multisite otherwise not.
