### ISSUE TITLE
dismiss-notice.js 404

### ISSUE THREAD

**Issue by SteveJonesDev** [afragen/wp-dependency-installer#70]
When used in a plugin to install other plugins its trying to load dismiss-notice.js from the themes vendor file rather than from the plugins vendor directory. Is there a way to tell it to pull from the plugin directory?

**Comment by SteveJonesDev** [comment]
Updating from version 3.1.0 to 4.3.5 fixed this issue.

**Comment by SteveJonesDev** [comment]
Reopening this issue as it still seems to be a problem even with the latest version. The dismiss-notice.js file is trying to load from the theme file when it should load from the plugin directory.

<img width="1086" alt="error-console-log-404" src="https://user-images.githubusercontent.com/2895788/228044958-ad58e4e2-6775-4fdd-b2cc-695b62ad0ecf.png">

**Comment by afragen** [comment]
That's not using my version, wp-dismiss-notice. Mine is https://github.com/afragen/wp-dismiss-notice

The referenced library is https://github.com/w3guy/persist-admin-notices-dismissal

**Comment by SteveJonesDev** [comment]
I see that now. Do you think this is a conflict if both are running on the same site? I'm only using yours.

![Screen Shot 2023-03-27 at 3 48 40 PM](https://user-images.githubusercontent.com/2895788/228050684-7a8aecc4-cc2f-4b95-ba21-ca6851513f67.png)

**Comment by afragen** [comment]
It shouldn't be as I think they can both co-exist.

**Comment by afragen** [comment]
The screenshot above doesn't match the console.log you posted.

**Comment by afragen** [comment]
What plugin is using the library?

**Comment by SteveJonesDev** [comment]
Accessibility Checker Pro is using dismiss-notice.js but I'm not sure what other theme or plugin on the customers website is using the other w3guy library. I gave you read access to our repo.

**Comment by afragen** [comment]
I think you're really going to like what I've got planned for WP 6.3. 

Take a look at the Plugin Dependencies feature plugin. What you would do is add the header `Requires Plugin: accessibility-checker` in the Pro header. That's it. 

BTW, did I miss meeting you at WordCamp Phoenix?

**Comment by SteveJonesDev** [comment]
Nice! I made it to WCUS and just spoke at WC Birmingham but didn't make it to Phoenix. Although, my business partner Amber Hinds was at Phoenix and spoke.

**Comment by afragen** [comment]
I think I saw Amber but missed opportunities to introduce myself.

**Comment by SteveJonesDev** [comment]
I heard a little about the Plugin Dependencies plugin in a podcast or something. But that will be really cool when rolled into core. Awesome work!

**Comment by afragen** [comment]
LMK what you think of Plugin Dependencies, though it will require WP6.3, assuming we get it committed.

**Comment by afragen** [comment]
Can you tell if the current functionality is not working? Regardless of the console.log error.

**Comment by SteveJonesDev** [comment]
The error is on a customer's website which I don't have access to yet. I've asked for access. I'm assuming the plugin is working but they are just getting this 404 error message. I wasn't able to reproduce the issue on my end.

**Comment by afragen** [comment]
I know I fixed a similar issue in my fork but don't think it's been incorporated in the original.

**Comment by SteveJonesDev** [comment]
I'm guessing it's from another plugin or theme.

**Comment by SteveJonesDev** [comment]
BTW, we just took in some funding from Joost (Yoast), so I'm looking for a full-time plugin developer to work on the Accessibility Checker. If you know anyone looking feel free to spread the word. 😀
