### ISSUE TITLE
Redundant?

### ISSUE THREAD

**Issue by afragen** [afragen/wp-dependency-installer#9]
@mgibbs189 is there some reason to use all this code when the following should work?

https://github.com/afragen/wp-dependency-installer/blob/develop/dependency-installer/wp-dependency-installer.php#L361-L373

``` php
WP_Dependency_Installer::instance()->register( $config );
```

instead of

``` php
WPDI()->register( $config );
```

**Comment by mgibbs189** [comment]
It's mostly for convenience. Either way is fine.

I use this approach for other plugins, especially ones with lots of public methods / properties.

E.g. It's easier for other developers to type `WPDI()->blah` than `WP_Dependency_Installer::instance()->blah` whenever they need access to something in the class.

**Comment by afragen** [comment]
I understand, but no one will really call this as the only thing we require is the dev include the `wp-dependency-installer.php` file.
